[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "saluki"
dynamic = ["version"]
dependencies = [
    "ess-streaming-data-types",
    "confluent-kafka"
]
readme = {file = "README.md", content-type = "text/markdown"}
license-files = ["LICENSE"]

[project.scripts]
saluki = "saluki.main:main"

[project.urls]
"Homepage" = "https://github.com/ISISComputingGroup/saluki"
"Bug Reports" = "https://github.com/ISISComputingGroup/saluki/issues"
"Source" = "https://github.com/ISISComputingGroup/saluki"

[project.optional-dependencies]
dev = [
    "pyright",
    "ruff",
    "pytest",
    "pytest-cov"
]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
fail_under = 100
exclude_lines = [
  "pragma: no cover",
  "if TYPE_CHECKING:",
  "if typing.TYPE_CHECKING:",
  "@abstractmethod",
]
omit = ["main.py"]  # No logic here besides argparse


[tool.coverage.html]
directory = "coverage_html_report"

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--cov --cov-report=html -vv"

[tool.setuptools_scm]
